# Generated by Django 4.2.24 on 2025-09-12 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertrule',
            options={'verbose_name': 'Правило уведомления', 'verbose_name_plural': 'Правила уведомлений'},
        ),
        migrations.AlterModelOptions(
            name='kpirecord',
            options={'verbose_name': 'Запись KPI', 'verbose_name_plural': 'Записи KPI'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Цех', 'verbose_name_plural': 'Цеха'},
        ),
        migrations.AlterModelOptions(
            name='useractionlog',
            options={'verbose_name': 'Запись журнала действий', 'verbose_name_plural': 'Записи журнала действий'},
        ),
        migrations.AddField(
            model_name='kpirecord',
            name='cabinets_produced',
            field=models.IntegerField(default=0, verbose_name='Изготовлено шкафов'),
        ),
        migrations.AddField(
            model_name='kpirecord',
            name='dse_volume',
            field=models.IntegerField(default=0, verbose_name='Объем ДСЕ'),
        ),
        migrations.AddField(
            model_name='kpirecord',
            name='energy_consumption',
            field=models.FloatField(default=0.0, verbose_name='Потребление энергии (кВт·ч)'),
        ),
        migrations.AddField(
            model_name='kpirecord',
            name='inventory_level',
            field=models.IntegerField(default=0, verbose_name='Остатки на складе (ед.)'),
        ),
        migrations.AddField(
            model_name='kpirecord',
            name='material_utilization',
            field=models.FloatField(default=0.0, verbose_name='Использование материалов (%)'),
        ),
        migrations.AddField(
            model_name='kpirecord',
            name='plan_completion',
            field=models.FloatField(default=0.0, verbose_name='Выполнение плана (%)'),
        ),
        migrations.AddField(
            model_name='kpirecord',
            name='productivity_index',
            field=models.FloatField(default=0.0, verbose_name='Индекс производительности (%)'),
        ),
        migrations.AddField(
            model_name='kpirecord',
            name='quality_index',
            field=models.FloatField(default=0.0, verbose_name='Индекс качества (%)'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='condition',
            field=models.CharField(choices=[('gt', '>'), ('lt', '<'), ('gte', '>='), ('lte', '<='), ('eq', '=')], max_length=3, verbose_name='Условие'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='indicator',
            field=models.CharField(choices=[('downtime', 'Простои'), ('defect_rate', 'Брак'), ('equipment_load', 'Загрузка оборудования'), ('output', 'Выпуск')], max_length=20, verbose_name='Показатель'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='notify_email',
            field=models.BooleanField(default=False, verbose_name='Уведомлять по email'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='notify_in_app',
            field=models.BooleanField(default=True, verbose_name='Уведомлять в интерфейсе'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='threshold',
            field=models.FloatField(verbose_name='Пороговое значение'),
        ),
        migrations.AlterField(
            model_name='kpirecord',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='kpirecord',
            name='defect_rate',
            field=models.FloatField(verbose_name='Процент брака'),
        ),
        migrations.AlterField(
            model_name='kpirecord',
            name='downtime_hours',
            field=models.FloatField(verbose_name='Часы простоя'),
        ),
        migrations.AlterField(
            model_name='kpirecord',
            name='equipment_load',
            field=models.FloatField(verbose_name='Загрузка оборудования (%)'),
        ),
        migrations.AlterField(
            model_name='kpirecord',
            name='output',
            field=models.IntegerField(verbose_name='Объем выпуска'),
        ),
        migrations.AlterField(
            model_name='kpirecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.shop', verbose_name='Цех'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название цеха'),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='action',
            field=models.TextField(verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время действия'),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
