# Generated by Django 4.2.24 on 2025-09-12 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_alertrule_options_alter_kpirecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория складских позиций',
                'verbose_name_plural': 'Категории складских позиций',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название позиции')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('unit', models.CharField(choices=[('pcs', 'Штуки'), ('m', 'Метры'), ('kg', 'Килограммы'), ('pack', 'Упаковки'), ('set', 'Комплекты')], max_length=10, verbose_name='Единица измерения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.inventorycategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Складская позиция',
                'verbose_name_plural': 'Складские позиции',
            },
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='indicator',
            field=models.CharField(choices=[('downtime', 'Простои'), ('defect_rate', 'Брак'), ('equipment_load', 'Загрузка оборудования'), ('output', 'Выпуск'), ('inventory_level', 'Общий уровень остатков'), ('plan_completion', 'Выполнение плана'), ('quality_index', 'Индекс качества')], max_length=20, verbose_name='Показатель'),
        ),
        migrations.AlterField(
            model_name='kpirecord',
            name='inventory_level',
            field=models.IntegerField(default=0, verbose_name='Общий уровень остатков на складе (ед.)'),
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('reserved', models.IntegerField(default=0, verbose_name='Зарезервированное количество')),
                ('min_threshold', models.IntegerField(default=0, verbose_name='Минимальный порог')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.inventoryitem', verbose_name='Складская позиция')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.shop', verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Запись остатков',
                'verbose_name_plural': 'Записи остатков',
                'unique_together': {('item', 'shop', 'date')},
            },
        ),
    ]
