# Generated by Django 4.2.24 on 2025-09-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_inventorycategory_inventoryitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrecord',
            name='demand',
            field=models.IntegerField(default=0, verbose_name='Потребность'),
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='shortage',
            field=models.IntegerField(default=0, verbose_name='Дефицит'),
        ),
    ]
